### ISSUE TITLE
Hope it can support Vue3 and Nuxt3

### ISSUE THREAD

**Issue by howard-tzw** [ashwinkshenoy/vue-simple#12]

**Comment by ashwinkshenoy** [comment]
Thankyou for supporting Vuesimple.
I am currently working on migrating Vuesimple to support vue3.
Thankyou for your patience! 🙏

**Comment by ashwinkshenoy** [comment]
Vuesimple is available for Vue3. 
Branch:  [Vue 3 - v3/next](https://github.com/ashwinkshenoy/vue-simple) Version: 3.0.5+

Closing this! 🙏
