### ISSUE TITLE
showClose not working

### ISSUE THREAD

**Issue by rix1337** [ashwinkshenoy/vue-simple#13]
<img width="207" alt="image" src="https://github.com/ashwinkshenoy/vue-simple/assets/9930448/ef58754d-d258-48c8-8d34-748da5d131da">
Sending a toast like this will still yield a close Button in the frontend.

**Comment by ashwinkshenoy** [comment]
This issue has been fixed in `v3.0.6`
Thanks for raising this issue. 🙏
